name: Build and push Backend to GCP (production)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository ðŸ“¡
        uses: actions/checkout@v4

      - name: Setup NodeJS âœ¨
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install project dependencies ðŸ“¦
        run: npm ci

      - name: Unit tests ðŸ§ª
        run: npm run test:unit
  build-deploy:
    needs: test
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository ðŸ“¡
        uses: actions/checkout@v4

      - name: build-deploy action ðŸš€
        uses: ./.github/actions/build-deploy
        with:
          project_id: ${{ vars.PRODUCTION_PROJECT_ID }}
          project_zone: ${{ vars.PRODUCTION_PROJECT_ZONE }}
          registry_url: ${{ vars.PRODUCTION_REGISTRY_URL }}
          service_account: ${{ vars.PRODUCTION_SERVICE_ACCOUNT }}
          service_name: ${{ vars.PRODUCTION_SERVICE_NAME }}
          workload_identity_provider: ${{ vars.PRODUCTION_WORKLOAD_IDENTITY_PROVIDER }}